trigger:
  - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: 'Build Azure Function App'
    jobs:
      - job: Build
        displayName: 'Build Function App'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.x' # Specify the required .NET version
          - script: |
              dotnet restore
              dotnet build --configuration Release
            displayName: 'Build the Azure Function App'



- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: |
        dotnet test --configuration Release
      displayName: 'Run Tests'


# - stage: Deploy
#   displayName: 'Deploy to Azure'
#   jobs:
#   - job: Deploy
#     displayName: 'Deploy Function to Azure'
#     pool:
#       vmImage: 'windows-latest'
#     steps:
#     - task: AzureFunctionApp@1
#       inputs:
#         azureSubscription: '<Azure for Students>'
#         appType: 'functionApp'
#         appName: '<AzureFunction>'
#         package: '$(System.DefaultWorkingDirectory)/**/*.zip'
